# Generated by Django 5.1.1 on 2025-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_participant_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('celebration', 'Celebration')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
